name: JIRA Reference Verifier
on: [pull_request]

jobs:
  check:
    name: Check PR
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: rpm1984/jira-ref-gh-action-test@master
          with:
             project-name: 'HDW'